controllers/DishController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Dish;
use app\models\Ingredient;

class DishController extends Controller
{
    private const NEW_DISH_SUCCESS_ADD = 'Новое блюдо успешно добавлено';

    private const NEW_DISH_ERROR_ADD = 'Произошла ошибка при добавлении нового блюда';

    private const DISH_SUCCESS_DELETE = 'Блюдо успешно удалено';

    private const UPDATE_DISH_WITHOUT_NAME = 'Ошибка при обновлении. У блюда должно быть название';

    private const TOO_FEW_INGREDIENTS_FOR_UPDATE_DISH = 'Ошибка при обновлении. У блюда остается слишком мало ингредиентов';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['@'],
                    ]
                ]
            ]
        ];
    }

    public function actionCreate()
    {
        $dish_model = new Dish();

        $manage_dish_ingredients_list = Yii::$app->session->get('manage_dish_ingredients') ?? [];
        $message = Yii::$app->request->get()['message'] ?? null;

        if ($dish_model->load(Yii::$app->request->post())) {

            $manage_dish_ingredients_list = Dish::addNewInfoOnCreateProcess($dish_model, $manage_dish_ingredients_list);

            return $this->render('create', [
                'available_ingredient_list'=>Ingredient::getAvailableIngredientList($manage_dish_ingredients_list),
                'dish_model'=>$dish_model,
                'manage_dish_ingredients_list'=>Ingredient::mergeIngredientNamesOnIds($manage_dish_ingredients_list),
                'message'=>$message
            ]);

        } else {

            $manage_dish_ingredients_list = Dish::checkDiscardItemInIngredientList($manage_dish_ingredients_list);

            return $this->render('create', [
                'available_ingredient_list'=>Ingredient::getAvailableIngredientList($manage_dish_ingredients_list),
                'dish_model'=>$dish_model,
                'manage_dish_ingredients_list'=>Ingredient::mergeIngredientNamesOnIds($manage_dish_ingredients_list),
                'message'=>$message
            ]);
        }
    }



    public function actionUpdate($id)
    {
        $dish_model = $this->findDishModel($id);

        $update_dish_ingredients_list = $dish_model->getIngredientsIds();
        $message = Yii::$app->request->get()['message'] ?? null;

        if ($dish_model->load(Yii::$app->request->post())) {


            $add_results = Dish::checkAddIngredientToDish($dish_model, $update_dish_ingredients_list);

            if (!$add_results['success']) {
                return $this->redirect(['/dish/update/'.$id.'?message='.static::UPDATE_DISH_WITHOUT_NAME]);
            }

            $update_dish_ingredients_list = $add_results['modified_dish_ingredients_list'];

            return $this->render('update', [
                'available_ingredient_list'=>Ingredient::getAvailableIngredientList($update_dish_ingredients_list),
                'dish_model'=>$dish_model,
                'manage_dish_ingredients_list'=>Ingredient::mergeIngredientNamesOnIds($update_dish_ingredients_list),
                'message'=>$message
            ]);

        } else {

            $delete_results = Dish::checkDeleteIngredientFromDish($dish_model, $update_dish_ingredients_list);

            if (!$delete_results['success']) {
                return $this->redirect(['/dish/update/'.$id.'?message='.static::TOO_FEW_INGREDIENTS_FOR_UPDATE_DISH]);
            }

            $update_dish_ingredients_list = $delete_results['modified_dish_ingredients_list'];

            return $this->render('update', [
                'available_ingredient_list'=>Ingredient::getAvailableIngredientList($update_dish_ingredients_list),
                'dish_model'=>$dish_model,
                'manage_dish_ingredients_list'=>Ingredient::mergeIngredientNamesOnIds($update_dish_ingredients_list),
                'message'=>$message
            ]);
        }
    }


    public function actionDelete($id)
    {
        $this->findDishModel($id)->delete();
        return $this->redirect(['/admin?message='.static::DISH_SUCCESS_DELETE]);
    }


    public function actionSave()
    {
        return $this->redirect(Dish::saveNewDish());
    }


    private function findDishModel($id)
    {
        if (($dish_model = Dish::findOne($id)) !== null) {
            return $dish_model;
        } else {
            throw new NotFoundHttpException('Requested ingredient not exist');
        }
    }
}

controllers/IngredientController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Ingredient;
use yii\web\NotFoundHttpException;

class IngredientController extends Controller
{
    private const HAVE_DISHES_FOR_DELETE_INGREDIENT = "Удаление ингредиента недоступно, имеются блюда где он задействован. Устраните его из них";

    private const INGREDIENT_SUCCESS_DELETE = "Ингредиент успешно удален";

    private const INGREDIENT_SUCCESS_CREATE = "Ингредиент успешно добавлен";

    private const INGREDIENT_SUCCESS_UPDATE = "Ингредиент успешно отредактирован";

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['@'],
                    ]
                ]
            ]
        ];
    }

    public function actionCreate()
    {
        $ingredient_model = new Ingredient();
        return $this->manageAction($ingredient_model, [
            'view_name'=>'create',
            'success_message'=>static::INGREDIENT_SUCCESS_CREATE
        ]);
    }

    public function actionUpdate($id)
    {
        $ingredient_model = $this->findModel($id);
        return $this->manageAction($ingredient_model, [
            'view_name'=>'update',
            'success_message'=>static::INGREDIENT_SUCCESS_UPDATE
        ]);
    }

    public function actionDelete($id)
    {
        $linked_dishes = $this->findModel($id)->getDishes()->all();
        if (count($linked_dishes) > 0) {
            return $this->redirect(['/admin?message='.static::HAVE_DISHES_FOR_DELETE_INGREDIENT]);
        } else {
            $this->findModel($id)->delete();
            return $this->redirect(['/admin?message='.static::INGREDIENT_SUCCESS_DELETE]);
        }
    }

    private function manageAction($ingredient_model, $action_params)
    {
        if ($ingredient_model->load(Yii::$app->request->post()) && $ingredient_model->save()) {
            return $this->redirect(['/admin?message='.$action_params['success_message']]);
        } else {
            return $this->render($action_params['view_name'], [
                'ingredient_model' => $ingredient_model
            ]);
        }
    }

    private function findModel($id)
    {
        if (($ingredient_model = Ingredient::findOne($id)) !== null) {
            return $ingredient_model;
        } else {
            throw new NotFoundHttpException('Requested ingredient not exist');
        }
    }
}

views/admin/_dish_list.php
<?php
use app\helpers\UrlTransform;
use yii\helpers\Html;
use yii\grid\GridView;
?>

<?php
    echo GridView::widget([
        'dataProvider'=>$dish_index_data_provider,
        'columns'=>[
            [
                'attribute'=>'id',
                'headerOptions'=>['width'=>40],
                'contentOptions'=>[
                    'class'=>'admin-grid-id-param'
                ]
            ],
            [
                'attribute'=>'name',
                'label'=>'Название',
                'contentOptions'=>[
                    'class'=>'admin-grid-name-param'
                ]
            ],
            [
                'class'=>'yii\grid\ActionColumn',
                'headerOptions'=>['width'=>50],
                'template'=>'{update}{delete}',
                'buttons'=>[
                    'update'=>function ($url, $model) {
                        return Html::a('&#9998;', 'dish/update/'.UrlTransform::getIdFromUrl($url), ['class'=>'grid-table-button']);
                    },
                    'delete'=>function ($url, $model) {
                        return Html::a('&#10006;', 'dish/delete/'.UrlTransform::getIdFromUrl($url), ['class'=>'grid-table-button']);
                    }
                ]
            ]
        ],
        'summaryOptions'=>[
            'class'=>'admin-grid-summary'
        ],
        'layout'=>'{summary}{items}<div class="catalog-tile-pager">{pager}</div>',
        'rowOptions'=>[
            'class'=>'admin-grid-row'
        ],
        'tableOptions'=>[
            'class'=>'admin-grid-table'
        ],
        'options'=>[
            'class'=>'admin-grid-container'
        ]
    ]);
?>

views/admin/_ingredient_list.php
<?php
use app\helpers\UrlTransform;
use yii\helpers\Html;
use yii\grid\GridView;
?>

<?php
    echo GridView::widget([
        'dataProvider'=>$ingredient_index_data_provider,
        'columns'=>[
            [
                'attribute'=>'id',
                'headerOptions'=>['width'=>40],
                'contentOptions'=>[
                    'class'=>'admin-grid-id-param'
                ]
            ],
            [
                'attribute'=>'name',
                'label'=>'Название',
                'contentOptions'=>[
                    'class'=>'admin-grid-name-param'
                ]
            ],
            [
                'attribute'=>'hidden',
                'label'=>'Скрытый',
                'headerOptions'=>['width'=>90],
                'contentOptions'=>[
                    'class'=>'admin-grid-hidden-param'
                ],
                'content'=>function ($data) {
                    return ($data->hidden)?'Да':'Нет';
                }
            ],
            [
                'class'=>'yii\grid\ActionColumn',
                'headerOptions'=>['width'=>50],
                'template'=>'{update}{delete}',
                'buttons'=>[
                    'update'=>function ($url, $model) {
                        return Html::a('&#9998;', 'ingredient/update/'.UrlTransform::getIdFromUrl($url), ['class'=>'grid-table-button']);
                    },
                    'delete'=>function ($url, $model) {
                        return Html::a('&#10006;', 'ingredient/delete/'.UrlTransform::getIdFromUrl($url), ['class'=>'grid-table-button']);
                    }
                ]
            ]
        ],
        'summaryOptions'=>[
            'class'=>'admin-grid-summary'
        ],
        'layout'=>'{summary}{items}<div class="catalog-tile-pager">{pager}</div>',
        'rowOptions'=>[
            'class'=>'admin-grid-row'
        ],
        'tableOptions'=>[
            'class'=>'admin-grid-table'
        ],
        'options'=>[
            'class'=>'admin-grid-container'
        ]
    ]);
?>

views/admin/index.php
<?php
//use app\helpers\UrlTransform;
use yii\helpers\Html;
//use yii\grid\GridView;
$this->title = 'Административный раздел';
?>

<?php if (!empty($message)): ?>
    <div class="admin-message">
        <?= $message ?>
    </div>
<?php endif; ?>

<div class="admin-main-container">
    <div class="admin-dish-list">
        <h3>Блюда</h3>

        <?= $this->render('_dish_list', [
            'dish_index_data_provider'=>$dish_index_data_provider
        ]); ?>

        <?= Html::a('Добавить блюдо', '/dish/create', ['class'=>'standart-button admin-dish-add-button']) ?>
    </div>
    <div class="admin-ingredient-list">
        <h3>Ингредиенты</h3>
        <?= $this->render('_ingredient_list', [
            'ingredient_index_data_provider'=>$ingredient_index_data_provider
        ]); ?>

        <?= Html::a('Добавить ингредиент', '/ingredient/create', ['class'=>'standart-button admin-ingredient-add-button']) ?>
    </div>
</div>